// Local-only browser fixtures. No valid session or production mutation is used.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || "playwright");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const base = process.env.QA_BASE_URL || "http://localhost:3000";
if (!["localhost", "127.0.0.1"].includes(new URL(base).hostname)) throw new Error("Goal fixture QA is local-only");
const output = path.resolve("artifacts/visual-qa"); fs.mkdirSync(output, { recursive: true });
const initial = [
  { id:"g1", title:"Read one hundred foundational design papers", description:"Build a grounded reference library and retain concise notes for each paper.", type:"LONG_TERM", status:"ACTIVE", currentValue:40, targetValue:100, unit:"papers", color:"#6366f1", targetDate:"2030-12-15T12:00:00.000Z", category:{name:"Learning"}, milestones:[{id:"m1",title:"Complete first twenty-five papers",description:"Capture one paragraph of notes for each.",isCompleted:true,order:0,targetDate:"2029-03-01T12:00:00.000Z"},{id:"m2",title:"Complete fifty papers",isCompleted:true,order:1},{id:"m3",title:"Synthesize the full collection",isCompleted:false,order:2}] },
  { id:"g2", title:"Build a durable emergency reserve with a deliberately long title that must wrap cleanly", description:"Increase the recorded balance toward the real target.", type:"QUARTERLY", status:"ACTIVE", currentValue:12500, targetValue:50000, unit:"EUR", color:"#3b82f6", targetDate:"2025-01-15T12:00:00.000Z", category:{name:"Finance"}, milestones:[{id:"m4",title:"Reach the first reserve threshold",isCompleted:true,order:0}] },
  { id:"g3", title:"Complete the first Novus research cycle", description:"The first cycle is recorded as complete.", type:"MONTHLY", status:"COMPLETED", currentValue:100, targetValue:100, color:"#10b981", targetDate:"2026-08-30T12:00:00.000Z", milestones:[] },
  { id:"g4", title:"Prepare a long-form writing portfolio", description:"Paused while the research cycle is active.", type:"CUSTOM", status:"PAUSED", currentValue:12, targetValue:60, unit:"pieces", color:"#8b5cf6", milestones:[{id:"m5",title:"Select the first five pieces",isCompleted:false,order:0}] },
];
const coachPlan = { assessment:"The goal has a clear numeric destination and recorded progress.", suggestedMilestones:[{title:"Review the current position",timeframe:"This week",description:"Confirm the next recorded step."}], recommendedHabits:["Review the goal once each week"], recommendedActions:["Choose the next paper to read"], estimatedTimeline:"Several focused months", motivationalNote:"Keep the next step concrete." };

let browser;
(async()=>{
  browser=await chromium.launch({headless:true,channel:"chrome"});
  const context=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:1,colorScheme:"dark"});
  await context.addCookies([{name:"authjs.session-token",value:"local-goal-fixture",url:base}]);
  const page=await context.newPage(); let goals=structuredClone(initial); const mutations=[]; const errors=[];
  page.on("pageerror",e=>errors.push(e.message)); page.on("console",m=>{if(m.type()==="error"&&!m.text().includes("status of 500"))errors.push(m.text());});
  await page.route("**/api/**",async route=>{
    const request=route.request(),url=new URL(request.url()),method=request.method();
    if(url.pathname==="/api/auth/session")return route.fulfill({json:{user:{name:"David",email:"goals-qa@example.invalid"},expires:"2099-01-01"}});
    if(url.pathname==="/api/notifications")return route.fulfill({json:{notifications:[],unreadCount:0}});
    if(url.pathname==="/api/ai/goal-coach"){const body=request.postDataJSON();mutations.push({method,path:url.pathname,body});return route.fulfill({json:{plan:coachPlan}});}
    if(url.pathname==="/api/ai/chat")return route.fulfill({json:{reply:"Local Goals QA response."}});
    if(url.pathname!=="/api/goals")return route.fulfill({json:{}});
    if(method==="GET")return route.fulfill({json:goals});
    const body=request.postDataJSON();mutations.push({method,path:url.pathname,body});
    if(method==="POST"){const created={id:`created-${goals.length}`,status:"ACTIVE",currentValue:0,unit:null,category:null,...body,milestones:body.milestones.map((m,i)=>({id:`new-m${i}`,title:m.title,isCompleted:false,order:i}))};goals=[created,...goals];return route.fulfill({status:201,json:created});}
    if(method==="PATCH"&&body.currentValue===77)return route.fulfill({status:500,json:{error:"fixture failure"}});
    if(method==="PATCH"&&body.goalId){goals=goals.map(g=>g.id===body.goalId?{...g,currentValue:body.currentValue}:g);return route.fulfill({json:goals.find(g=>g.id===body.goalId)});}
    if(method==="PATCH"&&body.milestoneId){goals=goals.map(g=>({...g,milestones:g.milestones.map(m=>m.id===body.milestoneId?{...m,isCompleted:body.milestoneCompleted}:m)}));return route.fulfill({json:{message:"Updated"}});}
  });
  const capture=(name,fullPage=true)=>page.screenshot({path:path.join(output,`stage2c-${name}.png`),fullPage});
  await page.goto(`${base}/goals`,{waitUntil:"networkidle",timeout:120000});await page.getByRole("heading",{name:"Active direction"}).waitFor();
  await capture("desktop-populated");assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.equal(await page.getByRole("article").count(),4);assert.equal(await page.getByText("33%",{exact:true}).count(),1);assert.equal(await page.getByText("3",{exact:true}).count()>=1,true);assert.equal(await page.getByText(/overdue/).count(),1);

  const firstCard=page.getByRole("article").filter({hasText:"Read one hundred foundational design papers"});await firstCard.getByRole("button",{name:"View and update"}).click();await page.getByRole("dialog",{name:"Read one hundred foundational design papers"}).waitFor();
  await page.getByLabel("Current progress (papers)").fill("55");await page.getByRole("button",{name:"Update progress"}).click();assert.deepEqual(mutations.at(-1),{method:"PATCH",path:"/api/goals",body:{goalId:"g1",currentValue:55}});
  await page.getByRole("button",{name:"Complete milestone: Synthesize the full collection"}).click();assert.deepEqual(mutations.at(-1),{method:"PATCH",path:"/api/goals",body:{milestoneId:"m3",milestoneCompleted:true}});
  await page.getByLabel("Current progress (papers)").fill("77");await page.getByRole("button",{name:"Update progress"}).click();await page.getByText("Progress could not be updated. The previous value was restored.").waitFor();assert.equal(await page.getByText("55 papers",{exact:true}).count()>=1,true);
  await page.getByRole("button",{name:"Close goal details"}).click();assert.equal(await page.getByRole("dialog",{name:"Read one hundred foundational design papers"}).count(),0);

  await page.getByRole("button",{name:"New goal",exact:true}).click();await page.getByRole("dialog",{name:"New goal"}).waitFor();await page.getByLabel("Goal title").fill("Publish the first field guide");await page.getByLabel("Description").fill("Turn the research into a concise guide.");await page.getByRole("button",{name:"Quarterly",exact:true}).click();await page.getByLabel("Target value").fill("250");await page.getByLabel("Target date").fill("2031-04-10");await page.getByLabel("Milestones optional").fill("Complete the working outline");await page.getByRole("button",{name:"Add",exact:true}).click();await page.getByRole("button",{name:"Create goal",exact:true}).click();await page.getByText("Publish the first field guide").waitFor();const createMutation=mutations.findLast(item=>item.method==="POST"&&item.path==="/api/goals");assert.equal(createMutation.body.type,"QUARTERLY");assert.equal(createMutation.body.targetValue,250);assert.deepEqual(createMutation.body.milestones,[{title:"Complete the working outline"}]);
  const createdCard=page.getByRole("article").filter({hasText:"Publish the first field guide"});await createdCard.getByRole("button",{name:"Goal Coach"}).click();await page.getByRole("dialog",{name:"Goal Coach"}).waitFor();await page.getByText("AI guidance, not a measured forecast.").waitFor();await page.waitForTimeout(400);await capture("desktop-coach",false);assert.equal(mutations.at(-1).path,"/api/ai/goal-coach");await page.getByRole("button",{name:"Close Goal Coach"}).click();

  for(let i=0;i<12;i++)goals.push({id:`bulk-${i}`,title:`Long-range objective ${i+1} with enough detail to test a dense collection`,description:"Recorded direction without forecast data.",type:i%2?"MONTHLY":"LONG_TERM",status:i%4===0?"COMPLETED":"ACTIVE",currentValue:i*3,targetValue:100,unit:"steps",color:"#6366f1",targetDate:null,milestones:[]});
  await page.reload({waitUntil:"networkidle"});await page.getByRole("heading",{name:"Active direction"}).waitFor();await capture("desktop-many",false);
  for(const [width,height] of [[1024,850],[360,800],[390,844],[430,932]]){await page.setViewportSize({width,height});await page.waitForTimeout(250);await capture(`${width}x${height}`,false);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);if(width<1024){const nav=await page.getByRole("navigation",{name:"Mobile navigation"}).boundingBox();assert(nav&&nav.y+nav.height<=height+1);}}

  goals=[];await page.setViewportSize({width:390,height:844});await page.reload({waitUntil:"networkidle"});await page.getByText("No goals yet").waitFor();await capture("mobile-empty");assert.equal(await page.getByText("0%",{exact:true}).count(),1);await page.emulateMedia({reducedMotion:"reduce"});await page.waitForTimeout(100);await capture("mobile-reduced");assert.equal(await page.evaluate(()=>getComputedStyle(document.querySelector("main > div > div")).animationName==="none"),true);

  goals=structuredClone(initial.slice(0,2));const touch=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,colorScheme:"dark",isMobile:true,hasTouch:true});await touch.addCookies([{name:"authjs.session-token",value:"local-goal-touch",url:base}]);const touchPage=await touch.newPage();touchPage.on("pageerror",e=>errors.push(e.message));touchPage.on("console",m=>{if(m.type()==="error")errors.push(m.text());});
  await touchPage.route("**/api/**",async route=>{const request=route.request(),url=new URL(request.url());if(url.pathname==="/api/auth/session")return route.fulfill({json:{user:{name:"David"},expires:"2099-01-01"}});if(url.pathname==="/api/notifications")return route.fulfill({json:{notifications:[]}});if(url.pathname==="/api/goals"&&request.method()==="GET")return route.fulfill({json:goals});if(url.pathname==="/api/goals"&&request.method()==="PATCH"){const body=request.postDataJSON();return route.fulfill({json:{message:"Updated",body}});}return route.fulfill({json:{}});});
  await touchPage.goto(`${base}/goals`,{waitUntil:"networkidle",timeout:120000});await touchPage.getByRole("heading",{name:"Active direction"}).waitFor();const touchCard=touchPage.getByRole("article").filter({hasText:"Read one hundred foundational design papers"});await touchCard.getByRole("button",{name:"View and update"}).tap();await touchPage.getByRole("dialog",{name:"Read one hundred foundational design papers"}).waitFor();await touchPage.waitForTimeout(350);assert.equal(await touchPage.evaluate(()=>{const dialog=document.querySelector('[role="dialog"]');const layer=dialog?.parentElement?.parentElement;const nav=document.querySelector('[aria-label="Mobile navigation"]');return Number(getComputedStyle(layer).zIndex)>Number(getComputedStyle(nav).zIndex)}),true);await touchPage.screenshot({path:path.join(output,"stage2c-mobile-detail.png"),fullPage:false});await touchPage.getByRole("button",{name:"Close goal details"}).tap();const nav=await touchPage.getByRole("navigation",{name:"Mobile navigation"}).boundingBox();assert(nav&&nav.y+nav.height<=845);assert.equal(await touchPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await touch.close();
  assert.deepEqual(errors,[]);fs.writeFileSync(path.join(output,"stage2c-goals-checks.json"),JSON.stringify({checks:["desktop populated and dense","truthful average and date states","progress contract and rollback","milestone toggle contract","create contract and milestones","Goal Coach preserved and labeled","1024 and three phone widths","empty and reduced motion","touch detail and no overflow"],mutations,errors},null,2));console.log({checks:9,mutations:mutations.length,errors});await browser.close();
})().catch(async error=>{console.error(error);await browser?.close();process.exitCode=1;});
